spring:
  application:
    name: auth-service
  config:
    import: file:./src/main/resources/.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_SECRET_ID}
server:
  servlet:
    context-path: "/api/v1"
  port: 9090
logging:
  level:
    org:
      springframework:
        security: TRACE



