version: '3.7'

services:
  postgres-auth:
    image: postgres:12
    container_name: auth-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: auth_db
    ports:
      - "5432:5432"