version: '3.7'
services:
  postgres-auth:
    image: postgres:12
    container_name: auth-db
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: auth_db
    ports:
      - "5432:5432"

  kafka:
    image: confluentinc/cp-kafka
    hostname: kafka-broker
    container_name: kafka-broker
    ports:
      - "8081:8081"
    environment:
      KAFKA_CLUSTER_ID: 1
