version: '3.7'

services:
  postgres-auth:
    container_name: auth-db
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: auth_db
    ports:
      - '5432:5432'

